create table if not exists public.dna_results (
  id bigint generated by default as identity primary key,
  room text not null,
  team text not null,
  start bigint not null,
  "end" bigint not null,
  elapsed integer not null,
  score integer not null,
  errors integer not null default 0,
  finished boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.dna_results enable row level security;

drop policy if exists "dna_results_insert" on public.dna_results;
create policy "dna_results_insert" on public.dna_results
for insert to anon
with check (true);

drop policy if exists "dna_results_select" on public.dna_results;
create policy "dna_results_select" on public.dna_results
for select to anon
using (true);

create index if not exists dna_results_room_idx on public.dna_results(room);
